import type { BundleShimParams } from './types.js'

/**
 * Render a standalone bash shim that embeds an OpenAPI spec as base64 and
 * execs a runner package at startup. The generated shim exposes these
 * subcommands regardless of runner:
 *
 *  - `--show-spec`    Decode and print the embedded spec
 *  - `--spec-md5`     Print the md5 of the embedded spec
 *  - `--spec <path>`  Override the embedded spec at runtime
 *  - `install`        Symlink (or copy) itself into $XDG_BIN_HOME / $HOME/.local/bin
 *  - `uninstall`      Remove a previous `install`
 *  - `update`         Re-bundle from the original spec source in-place
 *
 * All other arguments are passed through to the runner.
 */
export function renderBundleShim(params: BundleShimParams): string {
  const {
    name,
    version,
    description,
    runnerPackage,
    kindLabel,
    runnerInvocation,
    installSuccessHint,
    specSource,
    specBase64,
    specMd5,
  } = params

  const prefix = kindLabel.toUpperCase()
  const safeName = shellSingleQuote(name)
  const safeVersion = shellSingleQuote(version)
  const safeDescription = shellSingleQuote(description)
  const safeSpecSource = shellSingleQuote(specSource.value)
  const specSourceKind = shellSingleQuote(specSource.kind)
  const safeMd5 = shellSingleQuote(specMd5)

  const headerSpecSource =
    specSource.kind === 'inline' ? '(inline — update unavailable)' : specSource.value

  const hintText = installSuccessHint ?? 'Run:  %s'
  const installHintBlock = `    printf >&2 '       ${hintText}\\n' "$LINK"`

  return `#!/usr/bin/env bash
# Generated by ${runnerPackage}
# Generator:   ${runnerPackage}
# ${kindLabel} name:    ${name}
# Version:     ${version}
# Description: ${description}
# Spec source: ${headerSpecSource}
# Spec MD5:    ${specMd5}
# Spec:        embedded as base64-encoded JSON (dereferenced OpenAPI v3)
set -euo pipefail

${prefix}_NAME=${safeName}
${prefix}_VERSION=${safeVersion}
${prefix}_DESCRIPTION=${safeDescription}
SPEC_SOURCE=${safeSpecSource}
SPEC_SOURCE_KIND=${specSourceKind}
SPEC_MD5=${safeMd5}

SPEC_B64='${specBase64}'

_self_path() {
  local src="\${BASH_SOURCE[0]}"
  local dir
  dir="$(cd "$(dirname "$src")" && pwd)"
  printf '%s/%s' "$dir" "$(basename "$src")"
}

_resolve_runner() {
  if command -v ${runnerPackage} >/dev/null 2>&1; then
    printf '${runnerPackage}\\n'
    return 0
  fi
  if command -v npx >/dev/null 2>&1; then
    printf 'npx --yes ${runnerPackage}\\n'
    return 0
  fi
  printf >&2 'Error: neither ${runnerPackage} nor npx was found on PATH.\\n'
  printf >&2 '       Install with: npm install -g ${runnerPackage}\\n'
  printf >&2 '       Or install Node.js (>= 18): https://nodejs.org\\n'
  return 127
}

if [[ "\${1:-}" == "--show-spec" ]]; then
  printf '%s' "$SPEC_B64" | base64 -d
  printf '\\n'
  exit 0
fi

if [[ "\${1:-}" == "--spec-md5" ]]; then
  printf '%s\\n' "$SPEC_MD5"
  exit 0
fi

_default_install_dir() {
  if [[ -n "\${XDG_BIN_HOME:-}" ]]; then
    printf '%s' "$XDG_BIN_HOME"
  else
    printf '%s/.local/bin' "\${HOME:-~}"
  fi
}

_is_in_path() {
  local dir="$1"
  case ":$PATH:" in
    *":$dir:"*) return 0 ;;
    *) return 1 ;;
  esac
}

if [[ "\${1:-}" == "install" ]]; then
  shift
  TARGET_DIR="$(_default_install_dir)"
  MODE="symlink"
  FORCE=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help)
        printf 'Usage: %s install [--dir <path>] [--copy] [--force]\\n' "$${prefix}_NAME"
        printf '\\n'
        printf 'Installs this binary into a directory on your PATH.\\n'
        printf '\\n'
        printf 'Options:\\n'
        printf '  --dir <path>   Target directory (default: \\$XDG_BIN_HOME or \\$HOME/.local/bin)\\n'
        printf '  --copy         Copy the file instead of creating a symlink\\n'
        printf '  --force        Overwrite an existing file at the destination\\n'
        exit 0
        ;;
      --dir) TARGET_DIR="$2"; shift 2 ;;
      --dir=*) TARGET_DIR="\${1#--dir=}"; shift ;;
      --copy) MODE="copy"; shift ;;
      --force) FORCE=1; shift ;;
      *)
        printf >&2 '%s install: unknown argument: %s\\n' "$${prefix}_NAME" "$1"
        exit 2
        ;;
    esac
  done

  SELF="$(_self_path)"
  mkdir -p "$TARGET_DIR"
  LINK="$TARGET_DIR/$${prefix}_NAME"

  if [[ -e "$LINK" || -L "$LINK" ]]; then
    if [[ "$FORCE" -ne 1 ]]; then
      printf >&2 '%s install: %s already exists. Pass --force to overwrite.\\n' "$${prefix}_NAME" "$LINK"
      exit 1
    fi
    rm -f "$LINK"
  fi

  if [[ "$MODE" == "copy" ]]; then
    cp "$SELF" "$LINK"
    chmod +x "$LINK"
    printf >&2 '%s install: copied to %s\\n' "$${prefix}_NAME" "$LINK"
  else
    ln -s "$SELF" "$LINK"
    printf >&2 '%s install: symlinked %s → %s\\n' "$${prefix}_NAME" "$LINK" "$SELF"
  fi

  if ! _is_in_path "$TARGET_DIR"; then
    printf >&2 '\\n'
    printf >&2 '%s install: warning — %s is not on your PATH yet.\\n' "$${prefix}_NAME" "$TARGET_DIR"
    printf >&2 '       Add this line to your shell rc (~/.bashrc, ~/.zshrc, or equivalent):\\n'
    printf >&2 '\\n'
    printf >&2 '         export PATH="%s:\$PATH"\\n' "$TARGET_DIR"
    printf >&2 '\\n'
    printf >&2 '       Then run:  exec \$SHELL   (or open a new terminal)\\n'
  else
${installHintBlock}
  fi
  exit 0
fi

if [[ "\${1:-}" == "uninstall" ]]; then
  shift
  TARGET_DIR="$(_default_install_dir)"
  FORCE=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help)
        printf 'Usage: %s uninstall [--dir <path>] [--force]\\n' "$${prefix}_NAME"
        exit 0
        ;;
      --dir) TARGET_DIR="$2"; shift 2 ;;
      --dir=*) TARGET_DIR="\${1#--dir=}"; shift ;;
      --force) FORCE=1; shift ;;
      *)
        printf >&2 '%s uninstall: unknown argument: %s\\n' "$${prefix}_NAME" "$1"
        exit 2
        ;;
    esac
  done

  SELF="$(_self_path)"
  LINK="$TARGET_DIR/$${prefix}_NAME"

  if [[ ! -e "$LINK" && ! -L "$LINK" ]]; then
    printf >&2 '%s uninstall: %s does not exist.\\n' "$${prefix}_NAME" "$LINK"
    exit 1
  fi

  if [[ "$FORCE" -ne 1 ]]; then
    if [[ -L "$LINK" ]]; then
      RESOLVED="$(readlink "$LINK" 2>/dev/null || true)"
      if [[ "$RESOLVED" != "$SELF" ]]; then
        printf >&2 '%s uninstall: %s is a symlink to %s, not to this binary. Pass --force to remove anyway.\\n' \\
          "$${prefix}_NAME" "$LINK" "$RESOLVED"
        exit 1
      fi
    elif ! cmp -s "$LINK" "$SELF"; then
      printf >&2 '%s uninstall: %s differs from this binary. Pass --force to remove anyway.\\n' "$${prefix}_NAME" "$LINK"
      exit 1
    fi
  fi

  rm -f "$LINK"
  printf >&2 '%s uninstall: removed %s\\n' "$${prefix}_NAME" "$LINK"
  exit 0
fi

if [[ "\${1:-}" == "update" ]]; then
  shift
  UPDATE_SPEC=""
  UPDATE_VERSION_OVERRIDE=""
  UPDATE_VERSION_SET=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help)
        printf 'Usage: %s update [--spec <url|file>] [--app-version <version>]\\n' "$${prefix}_NAME"
        printf '\\n'
        printf 'Re-fetches the original spec and rewrites this binary in-place.\\n'
        printf '\\n'
        printf 'By default, the new ${prefix}_VERSION tracks the spec.info.version of the freshly\\n'
        printf 'fetched spec — the bundled version is a snapshot of the API, not of the binary.\\n'
        printf '\\n'
        printf 'Options:\\n'
        printf '  --spec <url|file>        Use a different spec source (default: the one baked in at bundle time)\\n'
        printf '  --app-version <version>  Override the version written to the new shim\\n'
        exit 0
        ;;
      --spec)
        if [[ $# -lt 2 ]]; then
          printf >&2 '%s update: --spec requires a value\\n' "$${prefix}_NAME"
          exit 2
        fi
        UPDATE_SPEC="$2"
        shift 2
        ;;
      --spec=*)
        UPDATE_SPEC="\${1#--spec=}"
        shift
        ;;
      --app-version)
        if [[ $# -lt 2 ]]; then
          printf >&2 '%s update: --app-version requires a value\\n' "$${prefix}_NAME"
          exit 2
        fi
        UPDATE_VERSION_OVERRIDE="$2"
        UPDATE_VERSION_SET=1
        shift 2
        ;;
      --app-version=*)
        UPDATE_VERSION_OVERRIDE="\${1#--app-version=}"
        UPDATE_VERSION_SET=1
        shift
        ;;
      *)
        printf >&2 '%s update: unknown argument: %s\\n' "$${prefix}_NAME" "$1"
        exit 2
        ;;
    esac
  done

  UPDATE_SOURCE="\${UPDATE_SPEC:-$SPEC_SOURCE}"

  if [[ -z "$UPDATE_SOURCE" ]]; then
    printf >&2 '%s update: this binary was bundled from an inline spec — no remote source to refresh.\\n' "$${prefix}_NAME"
    printf >&2 '       Pass --spec <url|file> to update, or re-run "${runnerPackage} bundle" manually.\\n'
    exit 1
  fi

  if [[ "$SPEC_SOURCE_KIND" == "file" && -z "$UPDATE_SPEC" && ! -e "$UPDATE_SOURCE" ]]; then
    printf >&2 '%s update: baked-in spec file not found: %s\\n' "$${prefix}_NAME" "$UPDATE_SOURCE"
    printf >&2 '       Pass --spec <url|file> to override.\\n'
    exit 1
  fi

  RUNNER_STR="$(_resolve_runner)" || exit $?
  read -r -a RUNNER <<< "$RUNNER_STR"

  SELF="$(_self_path)"
  TMP="\${SELF}.update.$$"
  trap 'rm -f "$TMP"' EXIT

  VERSION_ARGS=()
  if [[ "$UPDATE_VERSION_SET" -eq 1 ]]; then
    VERSION_ARGS=(--app-version "$UPDATE_VERSION_OVERRIDE")
  fi

  printf >&2 '%s update: fetching %s ...\\n' "$${prefix}_NAME" "$UPDATE_SOURCE"
  if ! "\${RUNNER[@]}" bundle \\
        --source "$UPDATE_SOURCE" \\
        --name "$${prefix}_NAME" \\
        "\${VERSION_ARGS[@]}" \\
        --out "$TMP"; then
    printf >&2 '%s update: bundle failed, binary not modified.\\n' "$${prefix}_NAME"
    exit 1
  fi

  NEW_VERSION="$(grep -m1 "^${prefix}_VERSION=" "$TMP" 2>/dev/null | sed -E "s/^${prefix}_VERSION='(.*)'\$/\\1/")"
  [[ -z "$NEW_VERSION" ]] && NEW_VERSION="unknown"
  NEW_MD5="$(grep -m1 "^SPEC_MD5=" "$TMP" 2>/dev/null | sed -E "s/^SPEC_MD5='(.*)'\$/\\1/")"
  [[ -z "$NEW_MD5" ]] && NEW_MD5="unknown"

  mv "$TMP" "$SELF"
  chmod +x "$SELF"
  trap - EXIT

  if [[ "$NEW_MD5" == "$SPEC_MD5" ]]; then
    printf >&2 '%s update: spec unchanged (md5 %s), %s is up to date at version %s.\\n' \\
      "$${prefix}_NAME" "\${NEW_MD5:0:8}" "$SELF" "$NEW_VERSION"
  else
    printf >&2 '%s update: spec changed (md5 %s → %s), %s %s → %s.\\n' \\
      "$${prefix}_NAME" "\${SPEC_MD5:0:8}" "\${NEW_MD5:0:8}" "$SELF" "$${prefix}_VERSION" "$NEW_VERSION"
  fi
  exit 0
fi

SPEC_OVERRIDE=""
PASSTHROUGH=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --spec)
      if [[ $# -lt 2 ]]; then
        printf >&2 '%s: --spec requires a value\\n' "$${prefix}_NAME"
        exit 2
      fi
      SPEC_OVERRIDE="$2"
      shift 2
      ;;
    --spec=*)
      SPEC_OVERRIDE="\${1#--spec=}"
      shift
      ;;
    --)
      shift
      while [[ $# -gt 0 ]]; do
        PASSTHROUGH+=("$1")
        shift
      done
      ;;
    *)
      PASSTHROUGH+=("$1")
      shift
      ;;
  esac
done

if [[ -n "$SPEC_OVERRIDE" ]]; then
  SPEC_FILE="$SPEC_OVERRIDE"
else
  SPEC_FILE="$(mktemp -t "$${prefix}_NAME.XXXXXX.json")"
  trap 'rm -f "$SPEC_FILE"' EXIT
  printf '%s' "$SPEC_B64" | base64 -d > "$SPEC_FILE"
fi

RUNNER_STR="$(_resolve_runner)" || exit $?
read -r -a RUNNER <<< "$RUNNER_STR"

exec "\${RUNNER[@]}" \\
  ${runnerInvocation}
`
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}
